package com.hc.gqgs.pojo;

import java.util.Date;

public class CoupleAwart {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.c_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String cCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.photo_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String photoPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.hk_photo_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String hkPhotoPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.idCard_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String idcardPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.mc_picture3
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String mcPicture3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.state
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column couple_awart.time
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.tid
	 * @return  the value of couple_awart.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.tid
	 * @param tid  the value for couple_awart.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.c_code
	 * @return  the value of couple_awart.c_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getcCode() {
		return cCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.c_code
	 * @param cCode  the value for couple_awart.c_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setcCode(String cCode) {
		this.cCode = cCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.path
	 * @return  the value of couple_awart.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.path
	 * @param path  the value for couple_awart.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.photo_path
	 * @return  the value of couple_awart.photo_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getPhotoPath() {
		return photoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.photo_path
	 * @param photoPath  the value for couple_awart.photo_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.hk_photo_path
	 * @return  the value of couple_awart.hk_photo_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getHkPhotoPath() {
		return hkPhotoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.hk_photo_path
	 * @param hkPhotoPath  the value for couple_awart.hk_photo_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setHkPhotoPath(String hkPhotoPath) {
		this.hkPhotoPath = hkPhotoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.idCard_path
	 * @return  the value of couple_awart.idCard_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getIdcardPath() {
		return idcardPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.idCard_path
	 * @param idcardPath  the value for couple_awart.idCard_path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setIdcardPath(String idcardPath) {
		this.idcardPath = idcardPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.mc_picture3
	 * @return  the value of couple_awart.mc_picture3
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getMcPicture3() {
		return mcPicture3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.mc_picture3
	 * @param mcPicture3  the value for couple_awart.mc_picture3
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setMcPicture3(String mcPicture3) {
		this.mcPicture3 = mcPicture3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.state
	 * @return  the value of couple_awart.state
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.state
	 * @param state  the value for couple_awart.state
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column couple_awart.time
	 * @return  the value of couple_awart.time
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column couple_awart.time
	 * @param time  the value for couple_awart.time
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}