package com.hc.gqgs.pojo;

public class QuestioBank {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questio_bank.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questio_bank.type
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questio_bank.tid
	 * @return  the value of questio_bank.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questio_bank.tid
	 * @param tid  the value for questio_bank.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questio_bank.type
	 * @return  the value of questio_bank.type
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questio_bank.type
	 * @param type  the value for questio_bank.type
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}
}