package com.hc.gqgs.pojo;

import java.util.Date;


public class SecondVisa {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.s_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String sCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.state
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.data
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String data;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.photoPath
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String photopath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.time
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.remark
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column second_visa.xgAndAmMuch
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer xgandammuch;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.tid
	 * @return  the value of second_visa.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.tid
	 * @param tid  the value for second_visa.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.s_code
	 * @return  the value of second_visa.s_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getsCode() {
		return sCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.s_code
	 * @param sCode  the value for second_visa.s_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setsCode(String sCode) {
		this.sCode = sCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.state
	 * @return  the value of second_visa.state
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.state
	 * @param state  the value for second_visa.state
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.data
	 * @return  the value of second_visa.data
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.data
	 * @param data  the value for second_visa.data
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setData(String data) {
		this.data = data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.path
	 * @return  the value of second_visa.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.path
	 * @param path  the value for second_visa.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.photoPath
	 * @return  the value of second_visa.photoPath
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getPhotopath() {
		return photopath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.photoPath
	 * @param photopath  the value for second_visa.photoPath
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setPhotopath(String photopath) {
		this.photopath = photopath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.time
	 * @return  the value of second_visa.time
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.time
	 * @param time  the value for second_visa.time
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.remark
	 * @return  the value of second_visa.remark
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.remark
	 * @param remark  the value for second_visa.remark
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column second_visa.xgAndAmMuch
	 * @return  the value of second_visa.xgAndAmMuch
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getXgandammuch() {
		return xgandammuch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column second_visa.xgAndAmMuch
	 * @param xgandammuch  the value for second_visa.xgAndAmMuch
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setXgandammuch(Integer xgandammuch) {
		this.xgandammuch = xgandammuch;
	}

	@Override
	public String toString() {
		return "SecondVisa [tid=" + tid + ", sCode=" + sCode + ", state=" + state + ", data=" + data + ", path=" + path
				+ ", photopath=" + photopath + "]";
	}
}