package com.hc.gqgs.pojo;

public class TrafficPoclie {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_poclie.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_poclie.t_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String tCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_poclie.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column traffic_poclie.data
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	private String data;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_poclie.tid
	 * @return  the value of traffic_poclie.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_poclie.tid
	 * @param tid  the value for traffic_poclie.tid
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_poclie.t_code
	 * @return  the value of traffic_poclie.t_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String gettCode() {
		return tCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_poclie.t_code
	 * @param tCode  the value for traffic_poclie.t_code
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void settCode(String tCode) {
		this.tCode = tCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_poclie.path
	 * @return  the value of traffic_poclie.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_poclie.path
	 * @param path  the value for traffic_poclie.path
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column traffic_poclie.data
	 * @return  the value of traffic_poclie.data
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column traffic_poclie.data
	 * @param data  the value for traffic_poclie.data
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	public void setData(String data) {
		this.data = data;
	}
}