package com.hc.gqgs.mapper;

import com.hc.gqgs.pojo.QuestioBank;
import com.hc.gqgs.pojo.QuestioBankExample;
import com.hc.gqgs.pojo.QuestioBankWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestioBankMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	long countByExample(QuestioBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int deleteByExample(QuestioBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int deleteByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int insert(QuestioBankWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int insertSelective(QuestioBankWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	List<QuestioBankWithBLOBs> selectByExampleWithBLOBs(QuestioBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	List<QuestioBank> selectByExample(QuestioBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	QuestioBankWithBLOBs selectByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByExampleSelective(@Param("record") QuestioBankWithBLOBs record,
			@Param("example") QuestioBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") QuestioBankWithBLOBs record,
			@Param("example") QuestioBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByExample(@Param("record") QuestioBank record, @Param("example") QuestioBankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByPrimaryKeySelective(QuestioBankWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(QuestioBankWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table questio_bank
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByPrimaryKey(QuestioBank record);
}