package com.hc.gqgs.mapper;

import com.hc.gqgs.pojo.TrafficPoclie;
import com.hc.gqgs.pojo.TrafficPoclieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrafficPoclieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	long countByExample(TrafficPoclieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int deleteByExample(TrafficPoclieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int deleteByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int insert(TrafficPoclie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int insertSelective(TrafficPoclie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	List<TrafficPoclie> selectByExampleWithBLOBs(TrafficPoclieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	List<TrafficPoclie> selectByExample(TrafficPoclieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	TrafficPoclie selectByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TrafficPoclie record, @Param("example") TrafficPoclieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") TrafficPoclie record, @Param("example") TrafficPoclieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByExample(@Param("record") TrafficPoclie record, @Param("example") TrafficPoclieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByPrimaryKeySelective(TrafficPoclie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(TrafficPoclie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table traffic_poclie
	 * @mbg.generated  Wed Jan 10 09:50:14 CST 2018
	 */
	int updateByPrimaryKey(TrafficPoclie record);
}